### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by passwa11** [winezer0/knife-plus#1]
burp version 2023.11.1.2
error info

```
java.lang.NullPointerException: Cannot invoke "javax.swing.table.TableModel.addTableModelListener(javax.swing.event.TableModelListener)" because the return value of "javax.swing.JTable.getModel()" is null
	at burp.theme.BurpTableUI.installListeners(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.installUI(BasicTableUI.java:1432)
	at com.formdev.flatlaf.ui.FlatTableUI.installUI(FlatTableUI.java:129)
	at burp.theme.BurpTableUI.installUI(Unknown Source)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:740)
	at java.desktop/javax.swing.JTable.setUI(JTable.java:3655)
	at java.desktop/javax.swing.JTable.updateUI(JTable.java:3704)
	at java.desktop/javax.swing.JTable.<init>(JTable.java:707)
	at java.desktop/javax.swing.JTable.<init>(JTable.java:645)
	at config.ConfigTable.<init>(ConfigTable.java:34)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:60)
	at burp.Zgyt.ZZ(Unknown Source)
	at burp.Zh2i.Zs(Unknown Source)
	at burp.Zh2m.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)

```

knife-2.1.9-jdk8.jar

**Comment by FaithZSW** [comment]
我也是

**Comment by winezer0** [comment]
刚看到 消息，该问题处理先2023.11.左右的bp版本上，是开发接口的问题，需要进行优化。
如果使用的不是本增强版的独有功能，建议大家先转到knife原版地址，已让原作修复了。
knife-plus 需要基于knife进行增量修改，耗时可能较长

**Comment by winezer0** [comment]
预计本周末进行问题解决

**Comment by winezer0** [comment]
请测试一下  https://github.com/winezer0/knife-plus/releases/tag/v2.1.11

**Comment by FaithZSW** [comment]
可以使用了，感谢师傅

**Comment by FaithZSW** [comment]
> 请测试一下 https://github.com/winezer0/knife-plus/releases/tag/v2.1.11

可以使用了，感谢师傅

**Comment by winezer0** [comment]
> 可以使用了，感谢师傅
请问用的哪个版本
